version: "3"

services:
  python:
    container_name: "python-3"
    build:
      context: ./
      dockerfile: ./docker/python/Dockerfile
    volumes:
      - ./app:/app
      - ./data:/data
      - ./scraper:/scraper
  interface:
    container_name: "node"
    build:
      context: ./
      dockerfile: ./docker/node/Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./interface:/interface
